name: flutter_map_hemend
description: A package for `flutter_map` containing some useful plugins
version: 0.0.1
homepage: "hemend.com"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ">=2.2.0"
  bloc: ">=8.1.0"
  latlong2: ">=0.8.1"
  flutter_bloc: ">=8.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
